### ISSUE TITLE
Redundant indicator when using -newline

### ISSUE THREAD

**Issue by Naatan** [justjanne/powerline-go#10]
![image](https://user-images.githubusercontent.com/278649/29677330-cdfdf7c0-88c8-11e7-8776-12e7907dcf28.png)

**Comment by justjanne** [comment]
You can use -modules to remove this indicator in the original line, but powerline-go has to display some module in the lower line (or the shell just ignores that). Just a space isn’t counted either.

**Comment by Naatan** [comment]
What module would that one be?

**Comment by justjanne** [comment]
this is the "root" module, it shows % for user, or # for root.

**Comment by Naatan** [comment]
Thanks @justjanne
