### ISSUE TITLE
duration can't handle very short durations (in scientific format)

### ISSUE THREAD

**Issue by sanga** [justjanne/powerline-go#108]
`tsampson  Hardy  ~  %  Failed to convert '8.3208084106445312e-05' to a number `

I'm actually not quite sure how I managed to get a duration in that format (the same command doesn't repro for me). And I guess it's a bit of a fringe bug (I won't mind terribly if it's closed). But as the reason is probably pretty clear I thought I'd post it.

This is on zsh btw

**Comment by object88** [comment]
Can you share your configuration?

**Comment by sanga** [comment]
I don't really have that configuration anymore sorry. However you can see the problem via this:

```
$ ~/.local/bin/powerline-go -duration 8.32e-05 -shell bare -modules user,host,ssh,docker,cwd,perms,git,exit,root,duration                                                      0.004s
 tsampson  galois  ~  .config  fish  $  Failed to convert '8.32e-05' to a number 
```

How I exactly managed to get a command duration in scientific format I'm not quite sure. This has only happened to me once. I assume it's pretty unlikely to pop up
