### ISSUE TITLE
When KUBECONFIG has several values, only the first one is showed in the prompt

### ISSUE THREAD

**Issue by lzecca78** [justjanne/powerline-go#118]
Hi guys, i have enabled `kube` module in order to view in the prompt also kubernetes cluster name and the namespace currently used. I have several entries in KUBECONFIG environment value like:

```bash
export KUBECONFIG=~/.kube/config-1:~/.kube/config-2:~/.kube/config-3
```

### what is happening

I noticed that only the first element of the values (in the example above `~/.kube/config-1` ) is correctly showed in the prompt, while, when i switch the cluster to the `~/.kube/config-2` using `kubectx`  the prompt is not enriched with the kubernetes information at all (the prompt appears just like no kubernetes cluster has been found). 
I tried to change the ordering of the values and the problem always comes out when i switch to an element different from the first one.

### how it should behave

Switching the cluster with `kubectx` i should see the right prompt information regarding the selected cluster and namespace

**Comment by argoyle** [comment]
I actually opened a PR (#116 ) for this yesterday. Clone my `read-all-configs`-branch and `go build` and point to that binary of powerline-go until the PR is merged.

**Comment by lzecca78** [comment]
@argoyle  thanks a lot for this reference!
