### ISSUE TITLE
Adding windows support

### ISSUE THREAD

**Issue by strangebug** [justjanne/powerline-go#12]
Hi,

First of all, great work 👍 

I was wandering if you would consider a PR or making a few modification to add windows support. Actually, it almost support compilation on windows right off the bat. The only thing preventing it is a unix syscall in ``segment-readonly.go``.
```go
	if unix.Access(cwd, unix.W_OK) != nil {
		p.appendSegment("perms", segment{
			content:    fmt.Sprintf(" %s ", p.symbolTemplates.Lock),
			foreground: p.theme.ReadonlyFg,
			background: p.theme.ReadonlyBg,
		})
	}
```

So I made the modification
```go
	const W_USR = 0002
	// Check user's permissions on directory in a portable but probably slower way
	fileInfo, _ := os.Stat(cwd)
	if fileInfo.Mode()&W_USR != W_USR {
		p.appendSegment("perms", segment{
			content:    fmt.Sprintf(" %s ", p.symbolTemplates.Lock),
			foreground: p.theme.ReadonlyFg,
			background: p.theme.ReadonlyBg,
		})
	}
```
and it seems to work just fine (at least if you're using git-bash).

![powerline_gitbash_windows](https://user-images.githubusercontent.com/3474151/29692016-249f33f4-892e-11e7-96e0-de826ae7db19.png)

I made the change by adding a specific implementation for windows so I'm sure it doesn't break anything for Unix users. But it's not really necessary, what's your thought about that ?

It is not thoroughly tested but I don't mind testing some more and submit a PR ;-)

[More details](https://github.com/strangebug/powerline-go/commit/5b8a3bc2b1e69fbf13614cc24f17e0cd97217067)

**Comment by strangebug** [comment]
After installing a proper font from https://github.com/powerline/fonts. No more glitches ;)

![powerline-go](https://user-images.githubusercontent.com/3474151/29732882-f84cf5e4-89ea-11e7-9c51-7e892a7f8e23.jpg)

**Comment by justjanne** [comment]
Could you open a Pull Request for this?

**Comment by strangebug** [comment]
Sure, done.
