### ISSUE TITLE
Right prompt doesn't get cleared as expected

### ISSUE THREAD

**Issue by mstiles92** [justjanne/powerline-go#120]
I am using ```-eval -module-right git``` to move the git module to the right prompt, but when I change to a directory that does not contain a git repo, the right prompt does not get cleared.

Here are the lines added I to .zshrc. Notice in the screenshot that the right prompt sticks around even after navigating to a directory not containing a git repo:
```
function powerline_precmd() {
    eval "$($GOPATH/bin/powerline-go -error $? -shell zsh -eval -modules user,cwd,exit -modules-right git)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi
```
![git_module_right](https://user-images.githubusercontent.com/1377201/53703859-7964d580-3de4-11e9-8d66-d27eb2b07d05.png)

I figured this was just not clearing the RPROMPT variable, so I was able to fix this by adding ```unset RPROMPT``` to the ```powerline_precmd()``` function in .zshrc. Just wanted to pass this along, in case you wanted to handle it in the program.
```
function powerline_precmd() {
    unset RPROMPT
    eval "$($GOPATH/bin/powerline-go -error $? -shell zsh -eval -modules user,cwd,exit -modules-right git)
}
```

**Comment by pdf** [comment]
#134 should fix this for you @mstiles92 if you want to test it, let me know of any issues.
