### ISSUE TITLE
main.getValidCwd() breaks on cygwin

### ISSUE THREAD

**Issue by kylewolfe** [justjanne/powerline-go#123]
https://github.com/justjanne/powerline-go/blob/master/main.go#L95-L101

I receive this warning in almost every directory except `~`: `[powerline-go]Your current directory is invalid. Lowest valid directory:  `

I suggest the following possible fixes:

- Option to disable `valid directory` checking (is this overhead even needed?)
- Check if `$OSTYPE == cygwin`
  - Route through `cygpath -m $pwd`
  - Turn off `valid directory` check
- Provide a global CLI option for the user to provide the `cwd` or `pwd` that will work. Eg: ``` PS1="$($GOPATH/bin/powerline-go -modules="host,user,git,kube,cwd" -pwd $(cygpath -m `pwd`) -error $?)"```

I think the last option seems the cleanest, least invasive, and quickest to implement.

Related to #12.

**Comment by kylewolfe** [comment]
PR #124 has been submitted.

**Comment by justjanne** [comment]
Could you try this with the changed implementation now again?
