### ISSUE TITLE
Exit codes not shown

### ISSUE THREAD

**Issue by tillyboy** [justjanne/powerline-go#125]
While tinkering around with the command prompt, I somehow managed to bork the display of the exit codes.

With my config:

    powerline_args=(
      -shell zsh
      -error $?
      -numeric-exit-codes
      -eval
      -modules nix-shell,venv,user,ssh,cwd,exit,perms,hg,vgo
      -modules-right git,exit,jobs,time
      -cwd-max-depth 4
    )

    function powerline_precmd() {
      eval "$(powerline-go ${powerline_args[@]})"
    }

    function install_powerline_precmd() {
      for s in "${precmd_functions[@]}"; do
        if [ "$s" = "powerline_precmd" ]; then
          return
        fi
      done
      precmd_functions+=(powerline_precmd)
    }

    if [ "$TERM" != "linux" ]; then
      install_powerline_precmd
    fi

I get the following behaviour:

![Screenshot](https://user-images.githubusercontent.com/31419678/54495863-58be7480-48e8-11e9-887a-a027dbe05687.png)

En-/Disabling `-numeric-exit-codes` gives the exact same result.

A bit off-topic, but is there somewhere a short summary what the modules do? e.g. I have never heard of hg or vgo before, a short list of bullet points would be really helpful :)

**Comment by PicoSushi** [comment]
I had same trouble with `zsh`, config was as below.
```sh
function powerline_precmd() {
    if ! hash powerline-go 2>/dev/null; then
        return
    fi
    PS1="$(powerline-go -max-width 0 -colorize-hostname -error $? -shell zsh -modules aws,terraform-workspace,venv,user,host,ssh,cwd,perms,jobs,git,hg,exit -newline)"                                                                        
}
```

note: I solved this trouble by using `fish` ;)

**Comment by justjanne** [comment]
The `-error $?` part has to be executed on each run, in your case you added it as static variable.

This should fix it:

```
powerline_args=(
  -shell zsh
  -numeric-exit-codes
  -eval
  -modules nix-shell,venv,user,ssh,cwd,exit,perms,hg,vgo
  -modules-right git,exit,jobs,time
  -cwd-max-depth 4
)

function powerline_precmd() {
  eval "$(powerline-go -error $? ${powerline_args[@]})"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
  install_powerline_precmd
fi
```
