### ISSUE TITLE
Suggestion for easier installing and updating instructions. 

### ISSUE THREAD

**Issue by treeder** [justjanne/powerline-go#13]
Use `go get -u github.com/justjanne/powerline-go` to install, then just point to the binary in `$HOME/go/bin`, eg:

```sh
function powerline_precmd() {
    PS1="$(~/go/bin/powerline-go -error $? -shell zsh)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi
```

Then to update, just to do `go get -u github.com/justjanne/powerline-go`

**Comment by justjanne** [comment]
This would indeed be easier for people using go get to install and update, if that’s more common than the binary release (which I had assumed would be more common), then you’re right, we should change that.

**Comment by treeder** [comment]
Just realized that would only be for Go developers so probably not a great idea.

**Comment by justjanne** [comment]
So, I’ve looked at the statistics, and we have just over 300 downloads, but far over 600 clones.

I’m going to switch to your suggestion.
