### ISSUE TITLE
"-shorten-eks-names" argument flag not defined

### ISSUE THREAD

**Issue by kdwodc** [justjanne/powerline-go#137]
I've tried `go get -u github.com/justjanne/powerline-go` as well as downloading the latest binary release for Darwin x64, and I get the same error every time.

```flag provided but not defined: -shorten-eks-names```

This arguement is still in the README so I'm not sure what's happening.

**Comment by justjanne** [comment]
This actually seems like a bug caused by a recent PR which I didn’t catch in time, I’ll take care to look at it and fix it.

Thank you for reporting :)
