### ISSUE TITLE
How to customize prompt

### ISSUE THREAD

**Issue by abetar0** [justjanne/powerline-go#138]
It could be related to #110, there is a `%` at the end of prompt.
How to change this? I just installed this and no customization in `.zshrc`.
```
function powerline_precmd() {
   PS1="$($GOPATH/bin/powerline-go -error $? -shell zsh)"
}
```

**Comment by justjanne** [comment]
Just use
```
function powerline_precmd() {
   PS1="$($GOPATH/bin/powerline-go -error $? -shell zsh -modules env,user,host,ssh,cwd,perms,git,hg,jobs,exit)"
}
```

That’d remove the "root" module responsible for showing that.

**Comment by abetar0** [comment]
As long as I read README, `env` would be `venv`?

```
function powerline_precmd() {
   PS1="$($GOPATH/bin/powerline-go -error $? -shell zsh -colorize-hostname -modules venv,user,host,ssh,cwd,perms,git,hg,jobs,exit)"
}
```
This works fine for me.
anyway, it helped me a lot. Thank you so much!
