### ISSUE TITLE
Not working on Manjaro

### ISSUE THREAD

**Issue by ShadabFaiz** [justjanne/powerline-go#139]
After installing, this is what I'm getting:
![Powerline](https://user-images.githubusercontent.com/8160121/61341923-0a08f300-a866-11e9-9ce5-fda15508b315.png)

Do I need to install anything else?
OS: Manjaro KDE (18.0.4)

**Comment by Torkiliuz** [comment]
You'll need a font that supports powerline. "Hack" is one of those.

**Comment by ShadabFaiz** [comment]
Tried Hack Font...still not working. However, Powerline-shell works. I don't have to install powerline for this. right?

**Comment by justjanne** [comment]
You can’t just run it directly, you’ll need to follow the readme’s install instructions.
