### ISSUE TITLE
powerline-go displays lock icon in a directory that user has write privs to

### ISSUE THREAD

**Issue by jcolson** [justjanne/powerline-go#149]
https://imgur.com/3lSYDra

edited with new image link

**Comment by Prajjwal** [comment]
@jcolson Attached screenshot link is dead.

Would be helpful if you provided filesystem, and exact privs on pwd.

**Comment by jcolson** [comment]
> @jcolson Attached screenshot link is dead.
> 
> Would be helpful if you provided filesystem, and exact privs on pwd.

updated image with fresh, has all info asked
