### ISSUE TITLE
How to remove the user hostname and lock icon ?

### ISSUE THREAD

**Issue by ghost** [justjanne/powerline-go#151]
https://imgur.com/by8Usy1

Hello as I could not find how to do it, and it seems other people are struggling too :

https://www.youtube.com/watch?v=X7vJ9rSgGZ8&t=306s

Could you please update the documentation or provide solution on how to remove unwanted parts from the prompt.

**Comment by hicksy** [comment]
There are several modules loaded by default that form your prompt. 

```
-modules string
    	 The list of modules to load, separated by ','
    	 (valid choices: aws, cwd, docker, dotenv, duration, exit, git, gitlite, hg, host, jobs, kube, load, newline, nix-shell, node, perlbrew, perms, root, shell-var, ssh, svn, termtitle, terraform-workspace, time, user, venv, vgo)
    	 (default "nix-shell,venv,user,host,ssh,cwd,perms,git,hg,jobs,exit,root,vgo")
```

To modify this, pass in the `-modules` flag, with your desired modules. 

For example, I've used the default list above and omitted `user,host` to achieve a prompt without the user and hostname parts.

```bash
function _update_ps1() {
    PS1="$($GOPATH/bin/powerline-go -modules nix-shell,venv,ssh,cwd,perms,git,hg,jobs,exit,root,vgo -error  $?)"
}
if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```

![image](https://user-images.githubusercontent.com/785770/69049038-db0eb380-09f6-11ea-8a9b-b89fe0a2e6c7.png)
