### ISSUE TITLE
Problems with customization

### ISSUE THREAD

**Issue by smaav** [justjanne/powerline-go#154]
Hello.
I'm trying to customize some powerline-go options for example:
`
-cwd-max-depth
`
but as output I getting something like that (for each option):
`
\[\e[38;5;250m\]\[\e[48;5;240m\] \u \[\e[48;5;238m\]\[\e[38;5;240m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;238m\] \h \[\e[48;5;31m\]\[\e[38;5;238m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;31m\] ~ \[\e[48;5;236m\]\[\e[38;5;31m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;236m\] \$ \[\e[0m\]\[\e[38;5;236m\]\[\e[0m\] 
`

How I can fix that?

**Terminal:** zsh/oh-my-zsh
**System:** Fedora 31

**Comment by justjanne** [comment]
Please follow the install instructions in the README.

To run the binary standalone, e.g. to experiment with some options, use the `-shell bare` option, it simulates what it would look like as prompt.
