### ISSUE TITLE
"developer can not be verified"

### ISSUE THREAD

**Issue by AlexFinn** [justjanne/powerline-go#160]
macOS Catalina

If I use precompiled binaries I get this
<img width="530" alt="Screenshot 2019-12-12 at 16 50 50" src="https://user-images.githubusercontent.com/1990823/70717728-00de5e00-1d00-11ea-8c3c-ceb1f287db89.png">

**Comment by justjanne** [comment]
That’s expected.

To fix this, I’d have to pay ~100$/year for this project, buy a mac, and run the builds on my own mac. That’s obviously not an option.

**Comment by justjanne** [comment]
If you’re willing to donate 100$/year and a mac, it’d be possible, though.

**Comment by AlexFinn** [comment]
I had no desire to reproach myself for anything.
But I think it makes sense not to put out the precompiled binary for macOS. It doesn't work anyway.
But as you wish :)

**Comment by justjanne** [comment]
It does work – right-click, open >, run and it should work.

**Comment by AlexFinn** [comment]
OK. It doesn't work for me

**Comment by argoyle** [comment]
You might have to allow it to run anyway in Security & Privacy preferences.
