### ISSUE TITLE
venv module is displayed twice after update to 1.15.0

### ISSUE THREAD

**Issue by arjan-s** [justjanne/powerline-go#168]
After upgrading from 1.13.0 to 1.15.0, the venv module is displayed twice in my prompt.
The PS1 I'm using where this happens:
`/usr/bin/powerline-go -max-width 80 -cwd-max-depth 2 -error $? -numeric-exit-codes -modules ssh,user,cwd,venv,git,jobs,perms,exit`

**Comment by pbordron** [comment]
I have the same problem with conda 4.7.12.
When I activate a conda env, its name is displayed twice.

**Comment by sumanthratna** [comment]
I had the same issue with `pipenv`, so I uninstalled it and switched to plain `python3 -m venv` and there're still two names. It seems like this is an issue with all virtualenvs, because I believe I had the same issue with `conda` and `poetry`.

**Comment by bryant1410** [comment]
#161 seems to fix it

**Comment by justjanne** [comment]
Fixed thanks to #161
