### ISSUE TITLE
Make multiple path aliases combine

### ISSUE THREAD

**Issue by Nadock** [justjanne/powerline-go#170]
Currently when you supply the `-path-aliases` flag more than one it seems that only the last one is getting used and the others are ignored.

This means, as the number and complexity of the path aliases in our prompt config grows, it gets really messy to maintain. Currently I have only 5 aliases, but because they're all on the same line in my `fish_prompt.fish` file it looks like a lot and knowing at a glance if I already have an alias for something is basically impossible.

Suggestion is to change this so that when multiple `-path-aliases` flags are supplied, all of the aliases in each instance of the flag are used.

Eg: These two uses would be equivalent:
```bash
$> powerline-go -path-aliases \~/repos=@repos,\~/repos/project=@project

$> powerline-go -path-aliases \~/repos=@repos -path-aliases \~/repos/project=@project
```

**Comment by justjanne** [comment]
Sadly the library we use for parsing command line arguments currently doesn’t support this.

If you were using bash, I’d suggest using an associative array, and joining that to a string to automatically configure the option, but as far as I can see, [fish doesn’t support maps/hashes/associative arrays](https://github.com/fish-shell/fish-shell/issues/390).

So your best option would probably be making a plain array of path aliases, and iterating over them to join them to a variable, and then use `-path-aliases $pathaliases` in the call to powerline-go
