### ISSUE TITLE
Powerline shows virtual environment name twice

### ISSUE THREAD

**Issue by trbedwards** [justjanne/powerline-go#172]
I've noticed this problem when using conda environments. It appends the venv segment twice to the powerline status bar. This can be fixed by removing lines 31-36 in `segment-virtualenv.go`

**Comment by metcalfc** [comment]
This was fixed in #173. Might it be possible to roll a release with this included? I'm building from source to work around it which is fine. But a release would get picked up by brew and that would be awesome.

**Comment by justjanne** [comment]
Fixed thanks to #173
