### ISSUE TITLE
Option "-static-prompt-indicator" not working

### ISSUE THREAD

**Issue by lfom** [justjanne/powerline-go#176]
Hello! I have just found out powerline-go after trying powerline-shell but got disappointed about the time it takes to show the prompt after every command (I am running Pop!_OS 19.10 on an Atom x5-Z8350 processor with 4GB of RAM). I just hope the development is still active since there are many pull requests that should fix annoying bugs (like the dual venv display, etc).

I also tried to customize my prompt and it seems that the toggle "-static-prompt-indicator" isn't working: regardless of if it is used or not the final prompt ($) is also colored, although the documentation says:
> Always show the prompt indicator with the default color, never with the error color

Regards

**Comment by dswij** [comment]
Is the desired behavior for the "**-static-prompt-indicator**" option is as the picture below? I have linked a pull request if so. 

Seems that the flag only changes when "**-newline**" option is toggled. 

![with -static-prompt-indicator](https://user-images.githubusercontent.com/44697459/84892100-30af5980-b0c7-11ea-998c-562c02d5efae.png)

**Comment by lfom** [comment]
Yes, it is. Hopefully it will be merged soon. Thanks.

**Comment by lfom** [comment]
@justjanne I don't want to push or sound disrespectful, but I would be very happy if there is a new release for those who do not have go installed or don't want to build the lasted version manually. :slightly_smiling_face:

**Comment by lfom** [comment]
Thanks @dswij for the fix/PR and @justjanne for merging and the build. Kudos.
