### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by MilanDasek** [justjanne/powerline-go#179]
Hi,

is there a way how to change color of segments? I would like to change git branch color.

![image](https://user-images.githubusercontent.com/12279315/76711460-97138d00-6710-11ea-8e83-224e4d54e255.png)

Thank you

M

**Comment by micck** [comment]
You can create a `.json` file based on the [default.json](https://github.com/justjanne/powerline-go/blob/master/themes/default.json) found in the _themes_ directory. And than use with:
> `powerline-go … -theme /PATH/your-file-name.json`

Please note, that the `.json` suffix is required, elsewise _powerline-go_ won't load the config from the file.
