### ISSUE TITLE
Not working in VS Code

### ISSUE THREAD

**Issue by YenHungLai** [justjanne/powerline-go#185]
Hello, as you can see the prompt is grayed out in Windows 10 VS Code integrated terminal. I did `export TERM=xterm-256color`  and locale is set to UTF-8.

<img width="640" alt="Capture" src="https://user-images.githubusercontent.com/34381523/78440115-86c64200-762c-11ea-9618-751277820099.PNG">

Works fine in Mintty though.

**Comment by zoranpopovic** [comment]
I get the same gray view no matter what i try, but with gitbash on pretty much any windows terminal except for mintty.  it's all gray conemu or new windows terminal or VSC terminal.

**Comment by justjanne** [comment]
It seems to work fine for me, is this maybe an issue with windows?

![Screenshot_2020-04-24_093305](https://user-images.githubusercontent.com/3933349/80186650-a094ec80-860e-11ea-8671-1094447508d6.png)

**Comment by zoranpopovic** [comment]
yes, any msys2/mingw/cygwin based shell like bash for windows seems to have a problem with ansi color code interpretation.  more details here https://github.com/microsoft/terminal/issues/2837

**Comment by aedavelli** [comment]
I resolved it by upgrading git-for-windows to latest.
Update your git-for-windows to latest. Earlier TERM was defaulted to `cygwin` which supports only 16color. The MSYS2 runtime upgraded to Cygwin 3.1.4 where the TERM is defaults to `xterm-256color`.  Refer https://github.com/git-for-windows/git/releases

**Comment by rkraneis** [comment]
I see the same issue with the jansi based terminal in NetBeans. Other colorful output does work (ls, maven or even a vim session).

**Comment by CWempe** [comment]
I think this issue can be closed.

Maybe @rkraneis wants to create a separate issue for "jansi based terminal in NetBeans"?!
