### ISSUE TITLE
not showing symbols

### ISSUE THREAD

**Issue by Kurpii** [justjanne/powerline-go#187]
Hi everyone, 
maybe someone can help me with this. 
I installed powerline-go as described and the fonts, but something is wrong with the symbols
I am using zsh on a Macbook with OS X Catalina

![Bildschirmfoto 2020-04-12 um 19 36 42](https://user-images.githubusercontent.com/51701337/79075795-323e5900-7cf5-11ea-9b1c-2e716f14e8f8.png)

**Comment by sreyan32** [comment]
What font are you using for the terminal ?

**Comment by Kurpii** [comment]
Hi @sreyan32
I am using the Andale Mono

**Comment by Kurpii** [comment]
oh man, i'm just next level stupid. of course I have to change the font. 
sorry for that
