### ISSUE TITLE
Permission denied - linux

### ISSUE THREAD

**Issue by vadviktor** [justjanne/powerline-go#19]
Hey,

I wanted to see how well this prompt builder works, but the linux release versions just won't execute. Strangely saying `Permission denied`. File looks a good build though: `ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped`, and file exec bits are set (`-rwxr--r--`) by me, still they won't work. Am I missing something?

**Comment by justjanne** [comment]
Have you tried executing the file directly? If you run it with -shell bare as argument, it should print out the prompt directly

**Comment by vadviktor** [comment]
@justjanne yes, actually that's how I only tried. Still with the suggested argument I got that. Can you show how did you compile it? I have asked a friend of mine to try it out and he has no problem and we both use Arch linux. So I'm kinda clueless yet. Thanks!

**Comment by justjanne** [comment]
This is very unusual, can you share more about your distro? I’d be interested in trying to replicate the issue. But in any way, it should always be able to print a shell – maybe do chmod a+x just to try?

**Comment by justjanne** [comment]
If no response happens until Oct 26th, I'll close this issue due to inactivity, as I currently can't reproduce it.

**Comment by vadviktor** [comment]
This looks like to have gone away.
