### ISSUE TITLE
Missing space after ssh icon?

### ISSUE THREAD

**Issue by junaru** [justjanne/powerline-go#195]
Hello,
There seems to be a missing space after the ssh icon, is this intended?
![Screenshot from 2020-05-08 00-55-37](https://user-images.githubusercontent.com/59161/81348891-9ae7de00-90c7-11ea-9416-bf45f95f2ee2.png)

Using latest  powerline-go from git master with [DroidSansMonoSlashed](https://github.com/powerline/fonts/tree/master/DroidSansMonoSlashed).
I have tried it with [GoMono](https://github.com/powerline/fonts/tree/master/GoMono) too with same results.

**Comment by gapeevanton** [comment]
With `-condensed`:

![2020-07-02_06-07-1593649801](https://user-images.githubusercontent.com/2061151/86303478-b4238b80-bc2d-11ea-8683-57a551afcb76.png)

**Comment by justjanne** [comment]
Should be fixed now, if it occurs again, please re-open with more details
