### ISSUE TITLE
Powerline-go won't execute in an alpine container

### ISSUE THREAD

**Issue by pietervogelaar** [justjanne/powerline-go#199]
The latest version of powerline-go won't execute in an alpine container.

```
curl -sSL https://github.com/justjanne/powerline-go/releases/download/v1.17.0/powerline-go-linux-amd64 -o powerline-go
chmod u+x powerline-go
```

Executing this says:
```
bash: /usr/local/bin/powerline-go: No such file or directory
```

However, version `1.15.0` has no problems. What is changed?

**Comment by k1ng440** [comment]
try to build from source.

```
env GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build-v -a -installsuffix cgo
```

**Comment by buckley310** [comment]
The binary download for version 1.15 is statically linked. The binary download for version 1.18 is dynamically linked, but it is linked to files that alpine does not provide.

If you really want to avoid building it yourself, this seems to work when I test it in an alpine container. It modifies the binary:
```
$ wget https://github.com/justjanne/powerline-go/releases/download/v1.18.0/powerline-go-linux-amd64

$ apk add patchelf

$ patchelf --set-interpreter /lib/ld-musl-x86_64.so.1 ./powerline-go-linux-amd64

$ ./powerline-go-linux-amd64 
\[\e[38;5;250m\]\[\e[48;5;12........
```

**Comment by justjanne** [comment]
This should be fixed with the new releases, please double-check if the issue still occurs (and re-open if that’s the case)
