### ISSUE TITLE
Issues with WSL2 - Running but not configurable

### ISSUE THREAD

**Issue by relief-melone** [justjanne/powerline-go#209]
I just installed powerline go with Ubuntu 20.04 in WSL2. It looks perfect but sadly I am not able to configure it. If you try to call anything like e.g. 

```
powerline-go -cwd-max-depth 3
```

All you will get is

>>\[\e[38;5;250m\]\[\e[48;5;240m\] \u \[\e[48;5;238m\]\[\e[38;5;240m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;238m\] \h \[\e[48;5;237m\]\[\e[38;5;238m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;237m\] mnt \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;237m\] c \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;237m\] … \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;254m\]\[\e[48;5;237m\] media-center \[\e[48;5;161m\]\[\e[38;5;237m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;161m\]  init \[\e[48;5;130m\]\[\e[38;5;161m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;130m\] 29✎ \[\e[48;5;236m\]\[\e[38;5;130m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;236m\] \$ \[\e[0m\]\[\e[38;5;236m\]\[\e[0m\]

Not only the output is broken but the configuration will also not change. Seems to work fine with the default settings though

**Comment by dswij** [comment]
I am using bash in WSL2 too, and it seems to work fine for me. I am not sure what caused it and how to reproduce it. Maybe somehow you can give some more details?

**Comment by relief-melone** [comment]
No problem. What details would be helpful. It's basically nothing special. 

- Its a fresh Win10 2004 build 
- Ubuntu 20.04 installed on WSL2
- powerline was the first thing to be installed 
- Everything was done according to the documentation
- Using Bash as interface

**Comment by relief-melone** [comment]
OK Reinstalled wsl completely and went throgh everything step by step. Now it works. So I guess the problem was sitting infront of the machine.
