### ISSUE TITLE
Blank PS1 after exporting $PS1 or only displays ?'s

### ISSUE THREAD

**Issue by predatorian3** [justjanne/powerline-go#21]
Hello, I tried to install powerline-go by using the instructions provided I downloaded the Release Binary, and also using `go get`. Then I placed the following two functions in my `.bash_profile` or `.bashrc`

```
function _update_ps1() {
  PS1="$($GOBIN/powerline-go -error $?)"
}

if [ "$TERM" != "linux" ]; then
  PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

export PS1=$PROMPT_COMMAND
```
This shows a blank terminal with nothing displayed. 

This is by just supplying 
`export PS1=$($GOBIN/powerline-go -newline -error $?)` displays the following 
```
Last login: Tue Aug 29 10:31:14 on ttys002
 user01  M1711AF4  ~  $ 
 $ 
```

What am I doing wrong? 

Running
OSX with iTerm2 using Bash.

**Comment by justjanne** [comment]
To what terminal mode have you set iTerm2, and what does it output if you run `$GOBIN/powerline-go -shell bare` directly?

**Comment by predatorian3** [comment]
```
user01@M1711AF4 [08:05:00] ~
$ $GOBIN/powerline-go -shell bare
 user01  M1711AF4  ~  $  user01@M1711AF4 [08:05:15] ~
$
user01@M1711AF4 [08:05:17] ~
$ echo $TERM
linux
```

**Comment by justjanne** [comment]
Well, there’s your issue. Your $TERM is set to linux, which means your shell thinks it's a hardware terminal or a serial terminal.

Set your $TERM to xterm-256color (as the README tells you to) and it should work.

**Comment by abtris** [comment]
```
→ ~/go/bin/powerline-go -shell bare
 abtris  Ladislavs-MBP  ~  bin  dotfiles  themes  master  3✎  $ 
abtris@Ladislavs-MBP:~/bin/dotfiles/themes [git:master]
→ echo $TERM
xterm-256color
```
similar problem $TERM not work, powerline fonts installed.

**Comment by justjanne** [comment]
This is certainly unusual, it might take a few days to test for me (I don’t have access to a Mac myself).

**Comment by predatorian3** [comment]
What would you need us to do to help you test on a Mac and OSX since we have one?

**Comment by pytimer** [comment]
Hi, i also have the same question.
I downloaded the release Binary, move `powerline-go` to /usr/bin.

powerline-go version is v1.11.0.
OS version: elementary OS 0.4.1 Loki

```sh
$   powerline-go -shell bare
 pytimer  pytimer    ~  $    pytimer  pytimer    ~  $ 
$   echo $TERM
xterm-256color
```

**Comment by vivekkrsingh** [comment]
For MAC, I had same issue. Turns out this is more of a terminal **config problem then anything else.**
To fix just install powerline font and change the Non-ASCII Font on iterm preferences.

For details follow step 5 on this link : https://medium.com/@elviocavalcante/5-steps-to-improve-your-terminal-appearance-on-mac-osx-f58b20058c84

**Comment by ascotan** [comment]
confirmed. If you're using iterm2 you have to download and install the powerline fonts onto your mac and then change the font in your profile.
