### ISSUE TITLE
Segment Separator is shown as  (question mark inside a box)

### ISSUE THREAD

**Issue by shammishailaj** [justjanne/powerline-go#211]
I have installed this on my Mac OS 10.15.5 and instead of the character that points towards the right `>` a question mark inside a box is displayed. Please see the screenshot below.

<img width="408" alt="Screenshot 2020-06-23 at 8 14 24 PM" src="https://user-images.githubusercontent.com/3005292/85418308-42dd3c00-b58e-11ea-9a58-99dafe603a2c.png">

Probably is a font issue. Can someone guide me on how to fix it?

**Comment by shammishailaj** [comment]
Please ignore this issue. I was able to fix this myself by cloning the [fonts repository](https://github.com/powerline/fonts), installing the patched fonts and changing it in my terminal's preferences.

**Comment by deftdawg** [comment]
Turns out it's now possible to enable Powerline glyphs directly in iTerm2 @ `Preferences`-> `Profiles`->`Default`->`Use built-in Powerline glyphs`

<img width="599" alt="image" src="https://github.com/user-attachments/assets/4f7dbc91-3426-4b8c-a487-bf71f9737df7">
