### ISSUE TITLE
Buggy wrapping when dir name is too long (Windows Terminal)

### ISSUE THREAD

**Issue by andrzejnovak** [justjanne/powerline-go#216]
Wrapping when using powerline-go withing

![image](https://user-images.githubusercontent.com/13226500/87526095-ae489400-c68a-11ea-9803-73289fb86a2d.png)

Trying to go up through history makes it even more confusing.
![image](https://user-images.githubusercontent.com/13226500/87527050-db497680-c68b-11ea-83de-88eeb3b9ca16.png)

**Comment by justjanne** [comment]
You can configure how paths are supposed to be shortened or wrapped with the -cwd-max-depth, -cwd-max-dir-size, -max-width and -truncate-segment-width parameters. If that still doesn’t work, please re-open the issue.
