### ISSUE TITLE
'source .bashrc' causes performance issues

### ISSUE THREAD

**Issue by tahanemat** [justjanne/powerline-go#219]
How to reproduce:

execute the command: `source .bashrc`, powerline-go loads noticeably slower than before. Performance returns to normal when you restart terminal.

**Comment by buckley310** [comment]
If you used the code snippet from the readme to set up powerline, then each time you source ".bashrc", powerline runs an additional time each prompt. So if bash loads your bashrc at startup, then you manually load bashrc again, powerline will run twice at each prompt, thus taking twice as long.

If you require reloading bashrc multiple times, you may be better off using this slightly modified version of the bashrc snippet. It makes sure to only hook the prompt function once.
```
function _update_ps1() {
    PS1="$($GOPATH/bin/powerline-go -error $?)"
}

if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ] && [ -z "$PLGO_INITIALIZED" ]; then
    PLGO_INITIALIZED=yes
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

```

**Comment by tahanemat-logiciel** [comment]
Thanks for the insight, I had no idea it ran .bashrc multiple times if you manually source it

**Comment by tahanemat** [comment]
Thanks for the insight, I had no idea it ran .bashrc multiple times if you manually source it
