### ISSUE TITLE
Squares seen at the position of path arrows

### ISSUE THREAD

**Issue by FaridHub** [justjanne/powerline-go#222]
Followed the instructions from here https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup
to setup. Squares are seen, no idea how to remove them.

![image](https://user-images.githubusercontent.com/8111839/90223364-88e6ab80-de2b-11ea-8502-057d7230f486.png)

**Comment by andrzejnovak** [comment]
You're missing the powerline fonts

**Comment by dswij** [comment]
Look at this section from the tutorial link you provided:

 https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup#install-a-powerline-font
