### ISSUE TITLE
Installation failing with undefined: os.UserHomeDir

### ISSUE THREAD

**Issue by kaushalvivek** [justjanne/powerline-go#224]
`go/src/github.com/justjanne/powerline-go/segment-rbenv.go:56:16: undefined: os.UserHomeDir`

WS2 - Ubuntu 18.04 

Is there something I am missing?

**Comment by intoempty** [comment]
Check go version; it is probably ~1.10 but needs to be >1.12

**Comment by kaushalvivek** [comment]
Ah, I see. 1.10 is the latest version available through apt package installation for Ubuntu 18.04, I think. Will install >1.12 from binary, thanks!
