### ISSUE TITLE
Only show error once or clear error after enter/carriage return?

### ISSUE THREAD

**Issue by grtrout** [justjanne/powerline-go#230]
I apologize if I'm missing something obvious here, but when an error is returned, I'm not able to "clear" it until I run a successful command. In the example attached, you can see how _badcmd_ caused the "NOTFOUND" error to display. But I would like to be able to, for example, hit the enter key and have this cleared. Is this possible?

![bash](https://i.imgur.com/78cvn8S.png)

**Comment by dswij** [comment]
I believe this is not possible right now, maybe an improvement proposal? @justjanne

**Comment by justjanne** [comment]
This is something that'd need to be changed in the bash/zsh/fish script invoking powerline-go, but should probably be easy to do there.

**Comment by justjanne** [comment]
I’ve added information on this in the README, but be aware that it has certain other side-effects (for example, for other programs you might want to execute in your shell)
