### ISSUE TITLE
macOS Terminal.app opacity issue

### ISSUE THREAD

**Issue by csmith1210** [justjanne/powerline-go#232]
So using Terminal.app on macOS if you decrease the opacity of your background then the bars follow that reduction in opacity, but the separators do not. That's probably not very clear. Here's some images:

**100% Opacity**
<img src="https://i.imgur.com/kxp54VV.png" width="500" />

**80% Opacity**
<img src="https://i.imgur.com/YfoxO03.png" width="500" />

I'm not sure what, if anything, can be done because I'm not sure how `powerline-go` controls the colors/rendering.

**Comment by justjanne** [comment]
This can't really be changed, as for the seperators to work they have to have seperate foreground and background colors.

But you could set the seperator style to none, that'd remove the seperators. Wouldn't look as nice, but would definitely work better under these circumstances

**Comment by csmith1210** [comment]
Thanks, that’s what I figured. I’ll see how I like it with the separator style set to none.
