### ISSUE TITLE
The color bar breaks when a teminal starts

### ISSUE THREAD

**Issue by Mulliken** [justjanne/powerline-go#234]
I am using WSL Ubuntu. The font is `Cascadia Code PL`.

![image](https://user-images.githubusercontent.com/19218605/94632178-f34a9280-0297-11eb-9d57-f87249f85533.png)

Any hints or help would be appreciated!

**Comment by justjanne** [comment]
That's so weird, it definitely looks like an issue with the WSL Terminal

**Comment by Mulliken** [comment]
> That's so weird, it definitely looks like an issue with the WSL Terminal

Good point. I'll try to reinstall WSL.

**Comment by justjanne** [comment]
If the problem persists, please re-open the issue, otherwise I’ll close this for now
