### ISSUE TITLE
Add option to trim Active Directory / Domain Name from username

### ISSUE THREAD

**Issue by rglidden** [justjanne/powerline-go#235]
Running under PowerShell on a Active Directory domain-joined computer. The username displays as `DOMAIN\username`, where "DOMAIN" is the Active Directory name. Looking at powerline.go, it has some code that attempts to deal with this:

```golang
	hostnamePrefix := fmt.Sprintf("%s%c", p.hostname, os.PathSeparator)
	if strings.HasPrefix(p.userInfo.Username, hostnamePrefix) {
		p.username = p.userInfo.Username[len(hostnamePrefix):]
	} else {
		p.username = p.userInfo.Username
	}
```
But this only appears to handle cases where the computer is not joined to a domain and usernames are in the format `HOSTNAME\username`. I can see why knowing the domain name would be useful in some cases, but it's also annoying and redundant when all your machines are on the same Windows domain.

It would be nice to have an option to `-trim-windows-domain` that would optionally remove the `DOMAIN` part of the username, similar to what is already done for the hostname.

**Comment by mschneider82** [comment]
Can you test my pull if it works for you

**Comment by rglidden** [comment]
Works great! Thanks @mschneider82
