### ISSUE TITLE
undefined: os.UserHomeDir

### ISSUE THREAD

**Issue by Hinkepeet** [justjanne/powerline-go#237]
On a new WSL 2 Ubuntu 18.04 install, after installing go the installation of powerline-go fails:

```
go get -u github.com/justjanne/powerline-go
# github.com/justjanne/powerline-go
go/src/github.com/justjanne/powerline-go/segment-rbenv.go:56:16: undefined: os.UserHomeDir
```

Worked perfectly fine the last time I installed it.

**Comment by dswij** [comment]
What version of go are u using?

**Comment by Hinkepeet** [comment]
go version go1.10.4 linux/amd64

**Comment by dswij** [comment]
[os.UserHomeDir ](https://golang.org/pkg/os/#UserHomeDir) is added after go >= 1.12 

Try upgrading your go

**Comment by Hinkepeet** [comment]
That resolved it! Thank you!
