### ISSUE TITLE
add an option

### ISSUE THREAD

**Issue by mpup371** [justjanne/powerline-go#248]
hi,
I use powerline-go and I really like it.
would it be possible to add an option to not display the " $ " segment ? I think it's not really necessary with colorized prompt.

thx
jf

**Comment by buckley310** [comment]
You can customize which segments are shown with the `-modules` parameter.

**Comment by mpup371** [comment]
hi,
thx for your reply
I don't understand all the meanings of the names of the modules. Is there a documentation ? what is hg ?
I use path with only the last folder displayed, but it still add ">...>" before it. Can it be removed ?
thx
jf

**Comment by buckley310** [comment]
The "hg" segment is for Mercurial. You can remove it unless you use mercurial.

If I understand correctly, the current-directory segment is showing the full path but you want it to only show the last folder name? If so, then launch powerline with the `-cwd-mode=dironly` option.

**Comment by dswij** [comment]
> would it be possible to add an option to not display the " $ " segment ? I think it's not really necessary with colorized prompt.

Also, I believe that you are looking to not load the _root_ module. So removing _root_ from the loaded modules will do. If you are currently using the default list of modules to load , add `-modules "venv,user,host,ssh,cwd,perms,git,hg,jobs,exit"` option to overwrite the default.

**Comment by mpup371** [comment]
hi
thx for your advices :-)
maybe a documentation about each module ?
regards,
jf
