### ISSUE TITLE
Build error on i386 arch

### ISSUE THREAD

**Issue by eclipseo** [justjanne/powerline-go#25]
When trying to build powerline-go on an i386 platform the following error occurs:
```bash
cd /builddir/build/BUILD/powerline-go-1.5.0
/usr/lib/golang/pkg/tool/linux_386/compile -o $WORK/_/builddir/build/BUILD/powerline-go-1.5.0.a -trimpath $WORK -shared -goversion go1.9beta2 -p main -complete -installsuffix shared -buildid 8bfc5e3a9a1fa903d42882c8c7a0a3679ddd0928 -D _/builddir/build/BUILD/powerline-go-1.5.0 -I $WORK -I /usr/share/gocode/pkg/linux_386_shared -pack ./defaults.go ./main.go ./powerline.go ./segment-cwd.go ./segment-docker.go ./segment-exitcode.go ./segment-git.go ./segment-hg.go ./segment-hostname.go ./segment-jobs.go ./segment-perlbrew.go ./segment-readonly.go ./segment-root.go ./segment-ssh.go ./segment-time.go ./segment-username.go ./segment-virtualenv.go ./themes.go
# _/builddir/build/BUILD/powerline-go-1.5.0
./powerline.go:92:16: constant 9223372036854775807 overflows int
```

The corresponding lines:

https://github.com/justjanne/powerline-go/blob/36489f503372ca86c70114775158d487b9c188a3/powerline.go#L91-L93

It seems math.MaxInt64 overflow on 32Bit system?

**Comment by justjanne** [comment]
Could you try now again, it should be fixed now (Go doesn’t provide an arch-dependent MaxInt constant, so I had to build my own for this, which I originally wanted to avoid)

**Comment by eclipseo** [comment]
Hello,

First, thanks for your quick response!

And yes, it works, it has successfully built on all my targeted arches: https://koji.fedoraproject.org/koji/taskinfo?taskID=21615516 

Will you do a v1.5.1 release for this or will you wait for another release?

Thanks again.

**Comment by justjanne** [comment]
I’m doing a v1.5.1 once other bugfixes I’ve been targeting for that release have been validated.

**Comment by justjanne** [comment]
Should be out now.
