### ISSUE TITLE
? for icons on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by dkirrane** [justjanne/powerline-go#254]
I followed the instructions [here](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup#set-up-powerline-in-wsl-ubuntu) but the prompt looks broken.
![image](https://user-images.githubusercontent.com/1280116/99263828-98550680-2817-11eb-8850-07e294106968.png)

In Windows Terminal I have `Cascadia Code PL` set:
```
           {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "fontFace": "Cascadia Code PL",
                "source": "Windows.Terminal.Wsl"
            }
```

**Comment by grtrout** [comment]
Do you see that font listed in "Font Settings" as well as in C:/Windows/Fonts? Are they still there following a reboot? I ask these questions because I had an issue like this where the font, despite appearing to be installed, was not actually installed.

**Comment by dkirrane** [comment]
Installed the [latest ](https://github.com/microsoft/cascadia-code/releases) rebooted. Working now thanks.
