### ISSUE TITLE
Support Xresources for themes

### ISSUE THREAD

**Issue by tobbbles** [justjanne/powerline-go#26]
Example .Xresources file:
```
! special
*.foreground:   #c5c8c6
*.background:   #1d1f21
*.cursorColor:  #c5c8c6

! black
*.color0:       #282a2e
*.color8:       #373b41

! red
*.color1:       #a54242
*.color9:       #cc6666

! green
*.color2:       #8c9440
*.color10:      #b5bd68

! yellow
*.color3:       #de935f
*.color11:      #f0c674

! blue
*.color4:       #5f819d
*.color12:      #81a2be

! magenta
*.color5:       #85678f
*.color13:      #b294bb

! cyan
*.color6:       #5e8d87
*.color14:      #8abeb7

! white
*.color7:       #707880
*.color15:      #c5c8c6
```

It'd be real nice if you could pass `-theme xresources`, and powerline-go would parse your xresources file and use those colors accordingly.

A note on xresources:
```
The colors 0-7 are the 'normal' colors. Colors 8-15 are their 'bright' counterparts, used for highlighting
```

**Comment by justjanne** [comment]
That’s up to the terminal. Powerline-go just specifies the color number (from 0 to 255, where 0-7 are normal colors, 8-15 bright colors, and 16-255 are additional colors), and the terminal then decides how to display them.

You could create an additional theme for powerline-go, though, which only uses 0-15.
