### ISSUE TITLE
Installation fails for Windows WSL Ubuntu 18.04

### ISSUE THREAD

**Issue by hobogalaxy** [justjanne/powerline-go#272]
**Describe the bug**
Installation fails for Windows WSL Ubuntu 18.04.

**To Reproduce**
What I did:
```bash
sudo apt-get update
sudo apt install golang-go
go get -u github.com/justjanne/powerline-go
```
Error I get on `go get -u github.com/justjanne/powerline-go`:
```
# golang.org/x/term
/home/ukasz/go/src/golang.org/x/term/term_unix_linux.go:9:26: ioctlReadTermios redeclared in this block
        previous declaration at /home/ukasz/go/src/golang.org/x/term/term_unix_aix.go:9:26
/home/ukasz/go/src/golang.org/x/term/term_unix_linux.go:10:27: ioctlWriteTermios redeclared in this block
        previous declaration at /home/ukasz/go/src/golang.org/x/term/term_unix_aix.go:10:27
```

**Environment:**
- Linux subsystem for Windows with Ubuntu 18.04 LTS
- Shell: bash

**Comment by justjanne** [comment]
This looks like golang.org/x/term is broken on WSL Ubuntu 18.04? If any other user has more information on this, I’d love to try to debug it, as this seems like a very weird issue.

**Comment by justjanne** [comment]
@hobogalaxy Your version of golang-go is too old. Please follow the official guide from the golang creators here https://github.com/golang/go/wiki/Ubuntu on how to install the correct version of golang:

```bash
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
sudo apt install golang-go
```
