### ISSUE TITLE
Bash powerline somehow broken after setting zsh as default shell (Manjaro/Arch)

### ISSUE THREAD

**Issue by fiechr** [justjanne/powerline-go#285]
This may not be a bug at all, but I don't know where to ask...

I've used the package manager to install powerline-go and it worked flawlessly with Bash as default shell for my user account. I'm using the Fira Code Nerd Font and the Plasma Konsole application as well as kitty terminal.

Yesterday I decided to try out zsh (without powerline-go for now) and switch the default shell using `chsh`. But if I now open a new window with Bash explicitly set as shell (while the default shell still being zsh), I only get this:
![powerline-go-issue01](https://user-images.githubusercontent.com/12040376/107203064-3ad9eb80-69fb-11eb-8d03-d606e818f9b1.jpg)

The font is still the same and `$TERM` is set to `xterm-256color`.  It's the same in Konsole and kitty. Shell looks fine, when I comment the added lines for powerline-go in the .bashrc.

Any ideas what could cause this?

**Comment by elig0n** [comment]
I've had powerline-go working great with bash until I upgraded it `go get -u github.com/justjanne/powerline-go` and I see strings similar to what you shown

**Comment by elig0n** [comment]
try to pass `-shell bash` in _update_ps1 function in your .bashrc

**Comment by fiechr** [comment]
Thanks!

**Comment by andrzejnovak** [comment]
Could this get pinned/added to README? I've spent way too long trying to reinstall everything several times thinking I was keeping some corrupted files somewhere

**Comment by scop** [comment]
I believe this may have been fixed with https://github.com/justjanne/powerline-go/pull/312.

Explicitly setting the shell isn't a bad idea when applicable though, as doing so avoids doing the shell detection repeatedly which might (or not) cause measurable amount of time spent on each run.
