### ISSUE TITLE
WSL - Symbols being replaced by unicode replacement character 

### ISSUE THREAD

**Issue by BerendvanWaalwijk** [justjanne/powerline-go#291]
![image](https://user-images.githubusercontent.com/37655274/110082183-4d8ed880-7d8d-11eb-8d95-025160bee9ec.png)

As seen in the screenshot, the dividing characters are being replaced. It occurs in both the visual studio terminal and the in-built linux terminal.

powerline-go latest
golang 1.13
ubuntu 20.04 running on windows subsystem for linux
TERM = xterm-256color

**Comment by dswij** [comment]
Did you use a powerline-font in any of the terminal?

**Comment by BerendvanWaalwijk** [comment]
> Did you use a powerline-font in any of the terminal?

I did just install it via the link in the readme. I've rebooted and rerun the ```_update_ps1```. This garners no effect

**Comment by dswij** [comment]
Have you changed your terminal settings so that it uses the installed font? This problem usually comes from the terminal not configured to use glyphs properly.

**Comment by BerendvanWaalwijk** [comment]
> Have you changed your terminal settings so that it uses the installed font? This problem usually comes from the terminal not configured to use glyphs properly.

I'm not quite sure what you mean. Can you elaborate?

**Comment by dswij** [comment]
Try: https://superuser.com/a/1508535

**Comment by BerendvanWaalwijk** [comment]
Appreciated.
