### ISSUE TITLE
Paths are not escaped correctly in Git BASH for Windows

### ISSUE THREAD

**Issue by CWempe** [justjanne/powerline-go#297]
**Describe the bug**
When using Git for Bash for Windows some paths are not escaped correctly which results in garbage being displayed.

![image](https://user-images.githubusercontent.com/1270359/111441288-7ad17400-8707-11eb-9566-d660d043721b.png)

The same works in PowerShell:

![image](https://user-images.githubusercontent.com/1270359/111441391-92a8f800-8707-11eb-8baf-b5fa28b44f89.png)

Path for copy: `~\AppData\Local\VirtualStore\ProgramData\chocolatey\lib\kitty\tools\Sessions`

**Environment (please complete the following information):**
 - OS: Windows 10
 - Architecture: 
 - Shell: Git Windows v2.30.1
 - powerline-go Version: v1.21

**Comment by avoidik** [comment]
Output of  `echo $PS1` may help to understand this behavior better

**Comment by CWempe** [comment]
Bash:

![image](https://user-images.githubusercontent.com/1270359/111890572-e60e9500-89ea-11eb-8957-0a95d638f809.png)


PowerShell: (useless I guess)

![image](https://user-images.githubusercontent.com/1270359/111890593-11917f80-89eb-11eb-89c9-faa686e6a16a.png)
