### ISSUE TITLE
Force a line break

### ISSUE THREAD

**Issue by Hayao0819** [justjanne/powerline-go#299]
**Describe the bug**
For example, if the standard output does not have line breaks, as in the code below, PowerLine-Go will delete and overwrite this output.

```bash
bash -c "printf Hello"
```

PowerLine written in Python forces a line break with the% symbol.

**Environment (please complete the following information):**
 - OS: Arch Linuix
 - Architecture: Intel x86_64
 - Shell: Zsh 5.8
 - PowerLine 1.21.0.12.gc6e1677-1

**Comment by dswij** [comment]
> PowerLine written in Python forces a line break with the% symbol.

It is doing as you described when I tried

![image](https://user-images.githubusercontent.com/44697459/111976589-c1c2cd80-8b3c-11eb-9d4f-2bcd02c8a55a.png)

Maybe I misunderstood. If so, can you give an example output and the expected one?

**Comment by Hayao0819** [comment]
Upon closer examination, this seems to be my zshrc issue, not the PowerLine-Go issue. I was able to solve it by editing my zshrc.
