### ISSUE TITLE
`-colorize-hostname` option not implemented?

### ISSUE THREAD

**Issue by falzm** [justjanne/powerline-go#3]
Hi

The usage help and the README advertise a `-colorize-hostname` flag to "Colorize the hostname based on a hash of itself", but it doesn't seem to be actually implemented. Can you confirm? And if so, I suggest pulling this flag from the code to avoid confusing users.

**Comment by justjanne** [comment]
This is correct, I planned to implement this function today.

It should be working within of the next 24 hours.

**Comment by justjanne** [comment]
This feature is included now, if it works for you, please close the issue.

**Comment by falzm** [comment]
It works for me, thank you.

**Comment by justjanne** [comment]
@falzm I decided to improve the feature further by generating much better color combinations, you might want to update the get the results.

**Comment by falzm** [comment]
My hostname's color didn't change with the new version, but if it better for you that's what matters 😉
