### ISSUE TITLE
Modified git branch name is same color as an error

### ISSUE THREAD

**Issue by treeder** [justjanne/powerline-go#30]
Should probably be a color that doesn't make you think it's an error. 

![screen shot 2017-09-14 at 9 07 04 am](https://user-images.githubusercontent.com/75826/30440691-291a9e4c-992c-11e7-9568-7d2ac8eb571b.png)

**Comment by justjanne** [comment]
I’m trying to stay backwards compatible the colorscheme of the powerline-shell python version,

**Comment by justjanne** [comment]
I’m trying to stay backwards compatible with the powerline-shell python version, and don’t want that if a user would switch over anything (including colorscheme) would be different.

Obviously, you can choose another theme, or change the default theme, if that resolves your issue.
