### ISSUE TITLE
No customization works

### ISSUE THREAD

**Issue by IsaacRWangPhysics** [justjanne/powerline-go#302]
I'm installing this powerline-go on my macOS Big Sur. My shell is zsh. I have golang version 1.16.2.

After I put the code in the .zshrc file, my powerline takes effect. However when I want to customize it, nothing works. It behaves like in the following figure:
<img width="801" alt="go-theme" src="https://user-images.githubusercontent.com/26316540/112365337-e9857300-8cad-11eb-916f-bce9d443c2d1.png">

<img width="800" alt="go-module" src="https://user-images.githubusercontent.com/26316540/112365357-edb19080-8cad-11eb-9a78-40622ad87d44.png">

How can I fix this?

**Comment by dswij** [comment]
Hi there, you should put your args for customization in your `~/.zshrc` rather than calling it directly

**Comment by IsaacRWangPhysics** [comment]
> Hi there, you should put your args for customization in your `~/.zshrc` rather than calling it directly

Sorry for the bothering. How can I call it in .zshrc? If I simply type `powerline-go -modules ...` it of course does not work. And the result is the same.

**Comment by IsaacRWangPhysics** [comment]
> Hi there, you should put your args for customization in your `~/.zshrc` rather than calling it directly

Thank you. I changed the part 
`function powerline_precmd(){PS1="..."}` Now it works.
