### ISSUE TITLE
powerline-go: command not found  

### ISSUE THREAD

**Issue by inkerinmaa** [justjanne/powerline-go#306]
![image](https://user-images.githubusercontent.com/5521235/113491325-8d55f680-94d8-11eb-9aa7-b8d11fa9ca11.png)
Hello
WSL2 Ubuntu 20.04 x64 on Windows 10 x64, Windows Terminal v1.6

After installing powerline-go and Cascadia fonts some text doesn't look like in preview at the main github page. Tried to use customization, typing powerline-go -help, but got an error - Command not found.

How to make this command works and how I can change colors of the text (now only Error highlighted and master branch, but address is in grey color)?

Thank you.

**Comment by justjanne** [comment]
I'm not sure where you installed the command, you'll likely have to run it as `$GOPATH/bin/powerline-go -help`

The parameter you'll likely want to add to the configuration is `-colorize-hostname`
