### ISSUE TITLE
Provide setting for low precision duration timers

### ISSUE THREAD

**Issue by pridkett** [justjanne/powerline-go#307]
**Is your feature request related to a problem? Please describe.**
While `bash` and `zsh` have timers that provide µs precision, `fish` does not. This means that every command that finishes in less than a second will say something like: `23ms 0µs`. Because everything is `0µs` for the microseconds, that doesn't provide any additional information and just ends up needlessly expanding the prompt.

**Describe the solution you'd like**
An optional argument on the command line of `-duration-low-precision` to indicate that the command duration timer is low precision, or maybe you just don't want to see `µs` in your other shells.

**Describe alternatives you've considered**
I have a [patch to completely remove µs that I've been maintaining for a couple of months](https://github.com/pridkett/ansible-role-powerline-go/blob/master/files/segment-duration.go.patch), but I realize that a command line flag might be better here.

**Additional context**
Here's an output of the proposed patch showing just the `duration` module (and using the default `fish` prompt for clarity):
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/160672/113494518-f462b380-94b6-11eb-8d31-0d82a47f693e.png">

**Comment by Cherkah** [comment]
@justjanne
first of all thank you for powerline-go.

 the parameter `-duration-low-precision`  is missing in the readme.
so can you update it

regards
