### ISSUE TITLE
Question about colorize-hostname setting

### ISSUE THREAD

**Issue by Hydranet** [justjanne/powerline-go#318]
The the customization section of the wiki there is the option to colorize the hostname.
```
Colorize the hostname based on a hash of itself, or use the PLGO_HOSTNAMEFG and PLGO_HOSTNAMEBG env vars
```
If was said in this other [issue](https://github.com/justjanne/powerline-go/issues/208#issuecomment-717304946) that I should use numbers, 0-255, for setting the variables.  I tried using the colors from this [color-chart](http://dmcritchie.mvps.org/excel/colors.htm).  When I set for example the BG color orange(46) and the FG color black(1), for the BG color I get green and for the FG color I get red. Which color chart do I use the get the right colors?

**Comment by vinithp** [comment]
check out this _/\_
https://jonasjacek.github.io/colors/

**Comment by Hydranet** [comment]
> check out this _/\_
> https://jonasjacek.github.io/colors/

Thank you that works! Will be added that to my bookmarks!
