### ISSUE TITLE
A clean install does not contain icons

### ISSUE THREAD

**Issue by Nuss9** [justjanne/powerline-go#322]
I followed this article from [Scott Hanselman](https://www.hanselman.com/blog/how-to-make-a-pretty-prompt-in-windows-terminal-with-powerline-nerd-fonts-cascadia-code-wsl-and-ohmyposh)  to install powerline-go on my WSL2 bash.
However, a clean install seems not to include the icons in my case, while I did expect them from the readme. 

Does anyone know where I could have a look?

![issue](https://user-images.githubusercontent.com/24221025/127338632-209cdaa4-8205-4a09-a79c-aa455144fa87.PNG)

**Comment by justjanne** [comment]
Quoting the README:

> If you want to use the "patched" mode (which is the default, and provides
improved UI), you'll need to install a powerline font, either as fallback,
or by patching the font you use for your terminal: see
[powerline-fonts](https://github.com/Lokaltog/powerline-fonts).
Alternatively you can use "compatible" or "flat" mode.

**Comment by Nuss9** [comment]
Got it! Also needed to set it, which I did via the settings: Ctrl + ,
