### ISSUE TITLE
Error info. by go1.17

### ISSUE THREAD

**Issue by wwdws1** [justjanne/powerline-go#324]
When I am using the command `go get -u github.com/justjanne/powerline-go` to get update with go 1.17, the information was given at below:

```
$ go get -u github.com/justjanne/powerline-go
go: downloading golang.org/x/crypto v0.0.0-20210817164053-32db794688a5
go: downloading golang.org/x/sys v0.0.0-20210820121016-41cdb8703e55
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/shirou/gopsutil v3.21.7+incompatible
go: downloading github.com/StackExchange/wmi v1.2.1
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

I think there is something abnormal, but I do not understand.
The OS info.: 
wsl2 Ubuntu20.04
Thank you again!

**Comment by dswij** [comment]
This works fine on Go 1.16.6. Seems like this happens because of 1.17. 😃 

Can you try using `go install github.com/justjanne/powerline-go@latest` instead?

Might need to update the README and CI soon.
