### ISSUE TITLE
Not working correctly with Git Bash in Windows Terminal

### ISSUE THREAD

**Issue by CWempe** [justjanne/powerline-go#329]
**Describe the bug**
I just started using [Windows Terminal](https://github.com/microsoft/terminal) .
Now I tried to integrate [Git Bash](https://gitforwindows.org/) into Windows Terminal.

Powerline-go already works fine with Git Bash: 👍 

![image](https://user-images.githubusercontent.com/1270359/133230151-4b608c5b-2286-4631-b44d-968ffced0899.png)

So does powerline-go with PowerShell in Windows Terminal. 👍 

![image](https://user-images.githubusercontent.com/1270359/133237246-93ff2a80-ceb8-4e1b-bbf3-d7de10cef245.png)

But poerline-go with Git Bash in Windows Terminal does not work correctly: 👎 

![image](https://user-images.githubusercontent.com/1270359/133237890-2f146b3b-e5c3-4e1f-9ff1-c85b78d75003.png)

**Environment:**

 - OS: Windows 10
 - Architecture: Intel
 - Shell: C:\Program Files\Git\bin\bash.exe

**Additional context**

This is my configuration in Windows Terminal:

```json
{
    "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
    "font": {
        "face": "DejaVuSansMono Nerd Font Mono",
        "size": 10
    },
    "guid": "{a3a012f0-aaa1-43d6-989f-0de3770b9e07}",
    "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
    "intenseTextStyle": "bright",
    "name": "Git Bash",
    "startingDirectory": "%USERPROFILE%",
    "useAcrylic": false
}
```

Any idea what could cause this issue?

Could be related to https://github.com/justjanne/powerline-go/issues/328, but I don't think so.
The issue looks different.

**Comment by mloskot** [comment]
Current `powerline-go` works very well in Git Bash in Windows Terminal, so I think this is not an issue any more - can be closed

![image](https://user-images.githubusercontent.com/80741/221378325-4b0c3999-d955-4ab0-b055-587838f6d344.png)

**Comment by mloskot** [comment]
Current `powerline-go` works very well in Git Bash in Windows Terminal, so I think this is not an issue any more - can be closed

![image](https://user-images.githubusercontent.com/80741/221378405-e65c7e87-5c19-4b59-b51a-a383e7858801.png)
