### ISSUE TITLE
Nice to have customizeable themes

### ISSUE THREAD

**Issue by boydkelly** [justjanne/powerline-go#372]
The current theme choices of gruvbox, and solarized are all brown/yellow -ish.   
It would be really great to have a ./config/powerline-go/theme file to support user themes.

At the very least include some more popular options that offer some variety:
nord:  calm green/bluish 
tokyo night: very popular dark theme
night-fly: Another popular dark choice

Obiously there are tons of shell themes out there.   Could powerline-go not just also read a theme definition from foot or alacrity or kitty terms?

**Comment by justjanne** [comment]
You should be able to do that already: https://github.com/justjanne/powerline-go/pull/251

**Comment by boydkelly** [comment]
Awesome!   Maybe this information could be added to the "customization" section of the readme.md.

**Comment by boydkelly** [comment]
Also we need some more details on how this works.   The example in https://github.com/justjanne/powerline-go/pull/251 contains a mode called 'wsl', which is also a segement.   And the valid 'modes' are indicated to be 'patched', 'compatible' or 'flat'.   So what is a 'wsl' mode?  In addition if I set the mode to 'flat', 
in both the ps1.sh and config.json, then the prompt displays as 'patched' (with powerline separators).   This happens if for example I just just the config.json in https://github.com/justjanne/powerline-go/pull/251 , but change the wsl to flat.        Shouldn't that just 'add' those parameters to the exisiting 'flat' mode?
