### ISSUE TITLE
No prompt in pyvenv.cfg makes venv incorrectly empty

### ISSUE THREAD

**Issue by matthubb** [justjanne/powerline-go#373]
The new ini check will incorrectly blank out `env` if there is no `prompt` value in the ini file.
https://github.com/justjanne/powerline-go/blob/fe0a2a494012c4edb7cc83e512d3efd1c7a7bc13/segment-virtualenv.go#L19

I'm not that familiar with golang, perhaps assigning the output of the ini lookup to a temporary value and checking it's not empty before overwriting `env` would suitably resolve this issue?

```golang
new_env = cfg.Section("").Key("prompt").String()
if new_env != "" {
        env = new_env
}
```

**Comment by elebertus** [comment]
https://github.com/justjanne/powerline-go/pull/387 - this change resolved the issue for me. Waiting for review.
