### ISSUE TITLE
Any plans to create new binaries?

### ISSUE THREAD

**Issue by jessehouwing** [justjanne/powerline-go#374]
There are a few fixes (the git perf ones for one), that I'd love to put on my system. Is there a new release planned anytime soon?

For the none-go'ers among us, are there manual steps I could perform to install from source instead of from binaries?

**Comment by justjanne** [comment]
I was planning to merge some more PRs before I do so, but sure, I can create a new release.

**Comment by jessehouwing** [comment]
No hurry! If a few more PRs, i can wait :).
