### ISSUE TITLE
Right prompt support

### ISSUE THREAD

**Issue by subpop** [justjanne/powerline-go#39]
I like to put my git info on a right prompt (yey fish). I can do it with `powerline-go -shell bare -mode flat -modules git`, and that looks fine, but would it be possible to add a `-prompt` option that maybe points the segment separator this way < instead of this way >?

**Comment by justjanne** [comment]
If you’re okay with building a custom version of it, you can change in defaults.go Separator to `` and SeparatorThin to ``

**Comment by yeled** [comment]
This looks great, thanks @pdf 

![image](https://user-images.githubusercontent.com/200421/42568693-e0130eb6-8505-11e8-938a-ad8579b2d829.png)

**Comment by kevwil** [comment]
I'd love to see this feature added, especially if it works for zsh. I miss my right prompt setup I had with the old Python-based powerline.

**Comment by pdf** [comment]
@kevwil the feature is available and working on zsh.
