### ISSUE TITLE
Python venv segment only showing when installed with `go install`

### ISSUE THREAD

**Issue by Sawy7** [justjanne/powerline-go#395]
Hey, first of all -- love your work, use it on all my machines!

For the longest time I thought the Python venv support was broken, but then I randomly tried to install the package using `go install` instead of the distro's package manager and it started working. I tried using the version from [AUR](https://aur.archlinux.org/packages/powerline-go) and [NIXPKGS](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/misc/powerline-go/default.nix), but the same thing happens - it's broken there.

Is there something more I need to install? Does the build work differently? Is this a bug? I would love for this to be managed by my package manager instead of sourcing it from my `$HOME`.

Thanks for your help!

**Comment by thespad** [comment]
It's fixed in https://github.com/justjanne/powerline-go/pull/387 but there's not been a release since then which is why distro packages won't have it but `go install` will.

**Comment by Sawy7** [comment]
> It's fixed in #387 but there's not been a release since then which is why distro packages won't have it but `go install` will.

That makes sense. Did not notice that. And now I see the new release is out. Closing, thanks!
