### ISSUE TITLE
Long directory name in path doesn't fully collapse

### ISSUE THREAD

**Issue by dschaper** [justjanne/powerline-go#42]
See attached, when in a directory that has a long path it appears that the prompt overwrites itself and drops the last directory to the leftmost position.

Fedora 26
GNOME Terminal
Bash
Installed via copr: eclipseo/powerline-go

.bashrc snip
```
# User specific aliases and functions

## Powerline-go
function _update_ps1() {
    PS1="$(/usr/bin/powerline-go -error $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```

![screenshot from 2017-10-12 08-49-12](https://user-images.githubusercontent.com/2782850/31505995-0dac9434-af2b-11e7-89a7-b8d215b8f7ae.png)

**Comment by robmv** [comment]
Nearly the same happen here with v1.7.1 but in this case it only shows the last line, the first part is missing/overwritten and doesn't show.

Output of `powerline-go` at /tmp

    \[\e[38;5;250m\]\[\e[48;5;240m\] \u \[\e[48;5;238m\]\[\e[38;5;240m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;238m\] \h \[\e[48;5;237m\]\[\e[38;5;238m\]\[\e[0m\]\[\e[38;5;254m\]\[\e[48;5;237m\] tmp \[\e[48;5;236m\]\[\e[38;5;237m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;236m\] \$ \[\e[0m\]\[\e[38;5;236m\]\[\e[0m\]

Output of `powerline-go` at /tmp/a/very/long/path

    \[\e[38;5;250m\]\[\e[48;5;240m\] \u \[\e[48;5;238m\]\[\e[38;5;240m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;238m\] \h \[\e[48;5;237m\]\[\e[38;5;238m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;237m\] tmp \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;237m\] a \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;237m\] very \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;250m\]\[\e[48;5;237m\] long \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;254m\]\[\e[48;5;237m\] path \[\e[48;5;236m\]\[\e[38;5;237m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;236m\] \$ \[\e[0m\]\[\e[38;5;236m\]\[\e[0m\]

Tried with another terminal implementation not based on vte (Visual Studio Code integrated terminal) with the same problematic behaviour.

**Comment by justjanne** [comment]
Could you try v1.7.3? This should fix this issue:

![screenshot_20171018_183737](https://user-images.githubusercontent.com/3933349/31730832-73be57d2-b433-11e7-967d-90401b9ccc83.png)

**Comment by robmv** [comment]
Sure. Tested and it isn't fixed here, see this session downloading 1.7.0, 1.7.1 and 1.7.3 and the output

![screenshot from 2017-10-18 13-54-12](https://user-images.githubusercontent.com/1652983/31734455-c56c12da-b40c-11e7-8bf9-55d4d9645ed1.png)

**Comment by justjanne** [comment]
I don’t see where the issue there is? It collapses segments based on what priorities you configured, and the default has the cwd segment with higher priority than the username segment.

So it first truncates segments based on priority, and, if that’s not possible anymore, it starts to remove segments based on priority.

**Comment by justjanne** [comment]
I'm planning to set separate priorities for the different parts of cwd in the next update.

cwd itself, and cwd-last for the current folder.

Then cwd itself would get lowest priority, and cwd-last the second highest.

Is that a working solution for you? Cutting down the path at first, until only the last part is left, then cutting down the rest?

**Comment by dschaper** [comment]
The problem that I am running in to is that when a long path is in the powerline-go prompt, the full path is displayed, but the terminal prompt drops back and overwrites the prompt, as seen on line one of the image, the `pwd` command is typing over the previously drawn powerline-go prompt.
![pwgo](https://user-images.githubusercontent.com/2782850/31739839-28058808-b404-11e7-87e3-7369044d5884.png)

**Comment by justjanne** [comment]
@dschaper Did you try with v1.7.3? And if yes, does this still occur?

This seems like there’s an issue with your terminals configuration.

**Comment by dschaper** [comment]
I'm running the lastest from the COPR repo.
```
sudo dnf info powerline-go
Last metadata expiration check: 1:15:05 ago on Wed 18 Oct 2017 11:47:32 AM PDT.
Installed Packages
Name         : powerline-go
Version      : 1.5.1
Release      : 1.fc26
Arch         : x86_64
Size         : 2.2 M
Source       : powerline-go-1.5.1-1.fc26.src.rpm
Repo         : @System
From repo    : eclipseo-powerline-go
```

**Comment by robmv** [comment]
@justjanne Splitting the priorities looks fine to me, thanks. For someone that works on long paths because of nested nature of Java packages, it is nice not to lose all other modules because the path is long

**Comment by robmv** [comment]
@dschaper you should try the binary on the release page at https://github.com/justjanne/powerline-go/releases/tag/v1.7.3 and then if fixed, ask the COPR repository maintainer to update it.

**Comment by dschaper** [comment]
Thanks will do.

**Comment by dschaper** [comment]
Powerline-go 1.7.3 fixes the collapse and closes my issue. Feel free to close it out, I have requested an updated package from COPR maintainer, but I don't want to close out this issue myself if there are other issues that need to be split off to a new issue. Thank you very much for the help.

**Comment by justjanne** [comment]
@robmv Could you try v1.8.0, and tell me if your issue is properly resolved?

**Comment by robmv** [comment]
Wonderful, even with more segments (git) the path is shortened:

     robert > __host__ > long > path > master > $

Thank you very much.
