### ISSUE TITLE
Collapse function partially functional

### ISSUE THREAD

**Issue by dschaper** [justjanne/powerline-go#45]
Version 1.8.1

The collapse now works but it seems to have issues and collapses out segments even when the terminal is wide enough to be able to handle them all. As soon as one segment collapses, additional segments are removed. 

Also seems to have lost the exit code detection.

![pw-go-collapse](https://user-images.githubusercontent.com/2782850/31784615-42ab4662-b4b7-11e7-9b7b-221f21243498.png)

**Comment by justjanne** [comment]
Can you share how you invoke it? The collapsing width and the exit code detection both can be configured.

It might just be an example of bad defaults.

**Comment by justjanne** [comment]
![screenshot_20171019_221833](https://user-images.githubusercontent.com/3933349/31792197-83ad2b76-b51b-11e7-970a-f1b7304b0129.png)

This is what I get on zsh, and I installed it with

```bash
export COLUMNS=$COLUMNS

function powerline_precmd() {
  export PS1="$(powerline-go -error $? -shell zsh -colorize-hostname)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

install_powerline_precmd
```

**Comment by dschaper** [comment]
```bash
## Powerline-go
function _update_ps1() {
    if [[ -x /usr/bin/powerline-go  ]]; then
       PS1="$(/usr/bin/powerline-go -error ${?})"
    fi
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```
```sh
echo $PS1
\[\e[38;5;250m\]\[\e[48;5;237m\] linux-shell… \[\e[48;5;237m\]\[\e[38;5;244m\]\[\e[0m\]\[\e[38;5;254m\]\[\e[48;5;237m\] localusers \[\e[48;5;236m\]\[\e[38;5;237m\]\[\e[0m\]\[\e[38;5;15m\]\[\e[48;5;236m\] \$ \[\e[0m\]\[\e[38;5;236m\]\[\e[0m\]
```
```sh
stty size
45 100
```

**Comment by justjanne** [comment]
This is exactly why I wanted to change the order in which to execute the powerline-go test — by running the -x test, you override the last exit code. Also, something is wrong with your tty size.

Could you try again by using the powerline_precmd that I posted above, including the weird re-exporting of $COLUMNS?

**Comment by dschaper** [comment]
Okay, have some progress and I think a nice workaround that fails nicely if the binary is not installed.

```bash
## Powerline-go
export COLUMNS=$COLUMNS
function _update_ps1() {
	if TMP_PS1=$(/usr/bin/powerline-go -error "${?}" -shell bash 2>/dev/null); then
		PS1="$TMP_PS1"
	fi
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```
![pwgo2](https://user-images.githubusercontent.com/2782850/31868585-558bda58-b755-11e7-8131-434889efa5e4.png)

**Comment by dschaper** [comment]
I'm still losing a lot of the modules due to collapse, so I tried using the newline flag, would it be possible to not collapse out functions when in newline mode and only truncate the `cwd` module?

**Comment by dschaper** [comment]
```bash
## Powerline-go
export COLUMNS=$COLUMNS
export PRIORITY=venv,git-status,git-branch,exit,host,ssh,perms,hg,jobs,cwd-path
function _update_ps1() {
		if TMP_PS1=$(/usr/bin/powerline-go -error "${?}" -shell bash -newline -priority "${PRIORITY}" 2>/dev/null); then
		PS1="$TMP_PS1"
	fi
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```

Seems to be a good setting.

**Comment by dschaper** [comment]
I've switched to a different package, feel free to close this one out if you'd like. Thanks for the great software though!
