### ISSUE TITLE
Modules disappeared after upgrading to version >1.7.0 on zsh with wsltty (1.8.0)

### ISSUE THREAD

**Issue by dannyk81** [justjanne/powerline-go#47]
I'm running powerline-go in zsh, using wsltty 1.8.0 (mintty 2.8.0) on a Windows 10 WSL (Windows Subsystem for Linux)

When upgrading to any version >1.7.0, most modules disappear from the prompt line (git, venv, etc..)

My terminal width has not changed, but it seems like powerline-go doesn't consider it has enough space to draw all the modules.

With v1.7.0 everything seems to work just fine.

**Comment by justjanne** [comment]
You can use `-max-width 0` to disable the scaling system. Otherwise you’ll have to re-export the $COLUMNS variable.

In the next version, the scaling system will be disabled by default, as apparently configuring it is complicated.

**Comment by dannyk81** [comment]
Thank you! that fixed it.
