### ISSUE TITLE
Double prompt when using as root

### ISSUE THREAD

**Issue by crdil** [justjanne/powerline-go#48]
When I use powerline-go as root use the prompt I'm getting looks like this
```_root@yose:/home/crdil\ 20:19:58  root  yose  home  crdil  SIGINT  # ```

For some reason I get a double prompt when using powerline when sudoing or su, I've added powerline to roots bashrc and commented out the standard PS1 in /root/.bashrc plus in /etc/bash.bashrc but I still get a double prompt.

Am I doing something wrong or is this a bug?

**Comment by justjanne** [comment]
This seems to be a configuration issue – it works fine for me, in any situation.

**Comment by crdil** [comment]
Ok, will have to try and  find where PS1 is set then. thanks anyway

**Comment by crdil** [comment]
Ok, will have to try and  find where PS1 is set then. thanks anyway
