### ISSUE TITLE
Git Error

### ISSUE THREAD

**Issue by AlexandreRoba** [justjanne/powerline-go#5]
I'm getting an error on a part of the git information.
Instead of showing the branch name it display "error"
I can see the number of untracked files properly.

How to reproduce:
```bash
mkdir projectname
cd projectname
git init (-> right after this the prompt display error instead of the branch name)
```
Once I add a file and start to track and commit it the error is removed and the proper branch is displayed.

Any idea?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60746/29635942-0efaab62-884f-11e7-8224-822d4a352fa6.png">

In the previous screen cap: 
* go-chat is a project wich is tracked and for wich the local branch is linked to a remote branch.
* cloud-native-app is a porject a just started and was not yet tracked...

**Comment by justjanne** [comment]
Can you check the latest version? It should fix this problem.

**Comment by AlexandreRoba** [comment]
Hi, Indeed. this solved the issue.
Thanks for the quick feedback and the nice work.
