### ISSUE TITLE
Please add a module that will display a specified shell variable

### ISSUE THREAD

**Issue by unixorn** [justjanne/powerline-go#51]
This would be great to display user-specific statuses. For example, I work with multiple AWS accounts and set an AWS_ACCOUNT environment in my shell that I use to display which AWS keypair is active in the shell session so I can see in the prompt if I've got the production keypair active.

**Comment by mexchip** [comment]
I've created a pull request for a module that can do this: #60.
You can check it/give it a try at https://github.com/mexchip/powerline-go/tree/shell-var

**Comment by mexchip** [comment]
@unixorn would you mind giving your opinion here #60?

**Comment by unixorn** [comment]
I'll take a look at it today
