### ISSUE TITLE
Theme not applying on linux

### ISSUE THREAD

**Issue by mikewaters** [justjanne/powerline-go#52]
I've modified the theme colors in my fork, and they apply fine on OSX.  However, when I install on linux, they don't apply.  I've learned that the colors in defaults.go are applied instead.  Any reason why this could be?  The $TERMs are the same, maybe I need to set some env var?

Not a huge problem, I just changed them in both places.

Thanks!

**Comment by mexchip** [comment]
As far as I can tell by having a look at the code (https://github.com/justjanne/powerline-go/blob/master/main.go#L190), theme is not read from an external file, only from the defaults.go file. I was thinking of adding a request for the implementation of the external file loading until I found your comment that it works in OSC, where is the .json file stored in your system?

**Comment by mikewaters** [comment]
@mexchip I have a fork and keep the source local, rebuilding it when I make changes.  So my theme is in $GOPATH/yadda/yadda/powerline-go/themes/mytheme.json

**Comment by mexchip** [comment]
I've just checked and theme loading works in my Linux system (Xubuntu 17.10), can you confirm?

**Comment by mexchip** [comment]
I think a section about loading a .json file should be added to the documentation.

**Comment by justjanne** [comment]
Considering this seems to be a bug with your own fork, I’ll close this bug
