### ISSUE TITLE
Git segment does not shown in Fish terminal when checkout to git branch with very long name

### ISSUE THREAD

**Issue by mgoku** [justjanne/powerline-go#54]
Git segment does not shown when checkout to git branch with very long branch name. Only happened in Fish terminal.

I test in Bash and ZSH, everything work fine.

Powerline-go version v1.8.2

![screenshot_20171124_195405](https://user-images.githubusercontent.com/1448244/33211480-4b23ba02-d151-11e7-8216-e71d1e717709.png)

**Comment by justjanne** [comment]
This is an issue where the width of the prompt becomes larger than the configured maximum. In the next version, this maximum limiter is removed, and the prompt will instead reflow over multiple lines.
