### ISSUE TITLE
cwd-mode dironly lead to hostname only

### ISSUE THREAD

**Issue by justDabuK** [justjanne/powerline-go#57]
adding the dironly option thorugh changing my .bshrc entry to 

```
function _update_ps1() {
         PS1="$(~/go/bin/powerline-go -cwd-mode dironly -error $?)"
    }
 
    if [ "$TERM" != "linux" ]; then
        PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
    fi
```

leads form this 
![bildschirmfoto von 2017-12-08 12-54-30](https://user-images.githubusercontent.com/26244739/33765013-3224248a-dc17-11e7-820c-8b9159848537.png)

to this 
![bildschirmfoto von 2017-12-08 12-55-29](https://user-images.githubusercontent.com/26244739/33765017-3aeffe68-dc17-11e7-8d4c-a1678f367adc.png)

Am I getting the dironly mode wrong? Or did I wrote the parameter I a wrong way? Because I expected it the other way around; the hostname disappeared and only the dir displayed. 

Would be nice if anyone could help me with this :).

**Comment by justjanne** [comment]
If the prompt is > 50% of the width of the terminal, it automatically gets truncated down.

In your situation, that's the case, so the directory will never be shown.

Additionally, dironly only changes how the directory module is shown — if you want to change what modules are shown (for example, to remove the hostname module), use the -module flag.

**Comment by justDabuK** [comment]
changing the list of modules was exactly what I needed, thank you :)

**Comment by treeder** [comment]
So what flag did you use to remove the hostname?
