### ISSUE TITLE
When powerline exceeds terminal's width it will disappear

### ISSUE THREAD

**Issue by muttleyxd** [justjanne/powerline-go#7]
```
mkdir -p dir1/dir2/dir3/dir4/dir5/dir6/dir7/dir8/dir9/dir10
cd -p dir1/dir2/dir3/dir4/dir5/dir6/dir7/dir8/dir9/dir10
git init
git checkout -b very-long-branch-name-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

After executing these powerline disappears for me, I'm not sure if that's the case in original.

While this example is a little overkill, this also can happen in real use - when using terminator and splitting terminals into half.

I use Fish Shell 2.6.0 on Manjaro Linux

**Comment by justjanne** [comment]
Which terminal emulator are you using? I can’t replicate this

![Screenshot showing powerline-go in zsh in Konsole breaking into multiple lines](http://i.imgur.com/0uj6MYL.png)

**Comment by muttleyxd** [comment]
It's called "terminator"

What I do is just split terminal window in half (split vertical hotkey) and then I go to the repository and it happens

**Comment by justjanne** [comment]
I tried in terminator, and it’s not an issue there either:

![Screenshot from terminator](http://i.imgur.com/1gHCn12.png)

It seems to be an issue of Fish Shell: [Prompt changes to ">" when fish thinks it's too long #904](https://github.com/fish-shell/fish-shell/issues/904)

But it seems like we should introduce a solution where we automatically truncate segments when the prompt becomes too long.

**Comment by muttleyxd** [comment]
Okay, thanks for your investigation - that's quite weird behavior of Fish, but I guess it probably will not be fixed considering how old the bug report is (2013).

**Comment by justjanne** [comment]
Would the suggested option above (removing segments by priority if the result would end up too long) work for you? If yes, I’d implement that.

**Comment by justjanne** [comment]
@muttleyxd I introduced now the priority system, which should automatically cut down the length of the shell, please try if this works for you.

**Comment by muttleyxd** [comment]
It seems like Fish overrides this behavior and does not call fish_propmt when terminal is too small. However after splitting few times in terminator Fish complains about terminal not being large enough and it starts working properly (until resize).

```
Welcome to fish, the friendly interactive shell
<W> fish: Current terminal parameters set terminal size to unreasonable value.
<W> fish: Defaulting terminal size to 80x24.
```

![fishy](https://user-images.githubusercontent.com/9843181/29700520-7ab3720a-8965-11e7-9960-940d81786183.png)

**Comment by justjanne** [comment]
I’m not sure if there’s anything else I can do here, but I’m gonna close this issue, and you’ll have to file one with the fish project.
