### ISSUE TITLE
Feature: time taken segment, for long-running commands

### ISSUE THREAD

**Issue by dbkaplun** [justjanne/powerline-go#71]
I would like a segment that shows how long the previous command took to execute. It would only appear if the command ran for ~20s or longer.

Thanks for considering!

**Comment by PicoSushi** [comment]
Great feature, I need it! I think this will be implementable like other tools, as https://github.com/popstas/zsh-command-time .

And, I'm working for this. (But, had [trouble](https://github.com/fish-shell/fish-shell/issues/5788) with fish shell...)
https://github.com/PicoSushi/powerline-go/tree/create-execution-time-segment

**Comment by justjanne** [comment]
You can add the duration module to your -modules, add a -duration parameter (getting the duration through something like this https://stackoverflow.com/questions/2704635/is-there-a-way-to-find-the-running-time-of-the-last-executed-command-in-the-shel), and add a -duration-min parameter to set the minimum duration to trigger this module to show up.

It’s not simple, it’s not entirely built in, but it works :)
