### ISSUE TITLE
funny character on ssh

### ISSUE THREAD

**Issue by JC1738** [justjanne/powerline-go#72]
Thank you for the project, works great.  Had a question, any suggestions to get it working over SSH?

![screenshot from 2018-02-18 16-52-18](https://user-images.githubusercontent.com/3421783/36359069-2a225b74-14cc-11e8-9428-e4764617e163.png)

I have tried to add local to the .ssh/config file, that didn't seem to help

**Comment by justjanne** [comment]
That looks like you’re missing the fonts required for the project – check in https://github.com/powerline/fonts or https://github.com/powerline/powerline/tree/develop/font to get the font.

**Comment by JC1738** [comment]
That was it, thanks! @justjanne
