### ISSUE TITLE
don't know what this flag means

### ISSUE THREAD

**Issue by deltaskelta** [justjanne/powerline-go#79]
Hi, nice tool, I use it on every machine!

I just saw something that I didn't know how to identify and I was wondering if you knew what it was. There is a small blue flag that appears when I am in one of my repos, and there is no reason for it that is apparent to me...

![screen shot 2018-04-22 at 4 42 23 pm](https://user-images.githubusercontent.com/9424192/39092610-e5e9b59e-464c-11e8-9a05-5133993b2f62.png)

I couldn't find any way to track down its meaning either, is there a centralized powerline standard anywhere that we could link to?

**Comment by maxadamo** [comment]
Same here! I can't understand what it is.

**Comment by deltaskelta** [comment]
I have figured it out...It is the number of stashes that you currently have. That is actually a really cool feature because I always stash and forget...

I just wish it was documented somewhere. Closing

**Comment by maxadamo** [comment]
thanks man! I do stash and forget as well (that's why I'm here with you)
