### ISSUE TITLE
Powerline adds excess spaces in prompt with some characters in the prompt content

### ISSUE THREAD

**Issue by nkudriavtsev** [justjanne/powerline-go#81]
Hello,

The cause of the error that you add spaces in output for EastAsianAmbiguous characters.

I made a quick patch to correct the issue for Greek and Cyrillic characters.

May be I missed something but I don't understand why you add extra spaces in prompt output for EastAsianAmbiguous character.
 
====
```
--- a/powerline.go
+++ b/powerline.go
@@ -185,7 +186,10 @@ func (p *powerline) numEastAsianRunes(segmentContent *string) int {
 		switch width.LookupRune(r).Kind() {
 		case width.Neutral:
 		case width.EastAsianAmbiguous:
-			numEastAsianRunes += 1
+			if !(0x370 <= r && r <= 0x3ff || // Greek and Coptic
+				0x400 <= r && r <= 0x4ff) { // Cyrillic
+				numEastAsianRunes += 1
+			}
 		case width.EastAsianWide:
 		case width.EastAsianNarrow:
 		case width.EastAsianFullwidth:

```

**Comment by justjanne** [comment]
> May be I missed something but I don't understand why you add extra spaces in prompt output for EastAsianAmbiguous character.

That was requested by a few users, because those characters are drawn as if they were 2 characters wide, but terminals only count them as one. So the prompt positioning was off.

**Comment by nkudriavtsev** [comment]
Fixed with -east-asian-width switch.
