### ISSUE TITLE
Color for the right-most separator is off

### ISSUE THREAD

**Issue by seelensonne** [justjanne/powerline-go#86]
The color for the right-most separator is slightly brighter than the background color of the segment preceding it (see yellow boxes in the screenshot; the screenshot uses the `low contrast` theme, but the situation is the same in the default theme):

![screenshot](https://user-images.githubusercontent.com/10898906/40639519-deaec208-6300-11e8-9935-c64b63d1aa3e.png)

I tried to tweak the conditional `separatorBackground` in [powerline.drawRow()](https://github.com/justjanne/powerline-go/blob/c9343401c162df54ca32d55e03c519831a8d06fe/powerline.go#L198), but unfortunately didn't quite manage to achieve the desired result (i.e., the right-most separator having the same color as the previous segment's background color).

@justjanne: Thank you for this great utility. And your readme is super nice and easy to follow too.

**Comment by justjanne** [comment]
Considering this issue doesn’t appear for me, or a few other users with whom I’ve tried this, I assume this is an issue with your shell or terminal emulator, sadly.

**Comment by saghul** [comment]
This happens to me only on Terminal.app on macOS, iTerm is fine, FWIW.
