### ISSUE TITLE
Kubernetes integration?

### ISSUE THREAD

**Issue by Savemech** [justjanne/powerline-go#89]
Anyone have  success using this awesome powerline along with https://github.com/jonmosco/kube-ps1 ?

**Comment by hassanshabbirahmed** [comment]
Why wouldn't you use the kube module? it does pretty much the same thing.

**Comment by justjanne** [comment]
In my own experience, the kube module has been good enough so far. If there’s anything specific you want from kube-ps1, I might be interested in implementing it.

**Comment by Savemech** [comment]
I did check kube module, and it's pretty cool, doing what I need; May this needs to be reflected in docs?
```
 -modules string
    	 The list of modules to load, separated by ','
    	    	 (valid choices: aws, cwd, docker, dotenv, exit, git, gitlite, hg, host, jobs, perlbrew, perms, root, shell-var, ssh, termtitle, time, user, venv, vgo)
    	    	 (default "venv,user,host,ssh,cwd,perms,git,hg,jobs,exit,root,vgo")
```

**Comment by aairey** [comment]
why closed?
