### ISSUE TITLE
Manual installation instructions not working for Ubuntu 18.04

### ISSUE THREAD

**Issue by phil-harmoniq** [justjanne/powerline-go#91]
I've been using powerline-go for a while in both macOS and Ubuntu 16.04 using manual installation into `~/.powerline` and using the instructions for installation have always worked for me using the following in by `~/.bash_aliases`:

```
function _update_ps1() {
    PS1="$(~/.powerline/powerline-go-linux-amd64 -error $?)"
}
export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
```

But after installing 18.04, this no longer works. The prompt is just the normal default Ubuntu prompt. I've tried all I could to figure out what is happening but have been unable to figure it out. I'm using the latest version available in the Releases tab. Let me know if I can give you any more information that would help.

**Comment by justjanne** [comment]
Ubuntu 18.04 and later use dash instead of bash, so your bash configuration won’t work anymore.

Change your shell to bash and it will.

**Comment by breml** [comment]
Based on [DashAsBinSh Wiki Page](https://wiki.ubuntu.com/DashAsBinSh#A.60dash.60_doesn.27t_expand_.60.2BAH4.60_on_path_search) maybe the problem is related to `~` instead of `$HOME`.

**Comment by justjanne** [comment]
@chipaca But not for the user-visible shell. Check /etc/passwd, that was changed in October 2017.

**Comment by chipaca** [comment]
I just booted the 18.04 desktop installer, added a user with `adduser`, with no extra options, and its shell was `/bin/bash`. I then installed it, and the resulting user has bash as its default shell. I then added another user using the graphical tool available, bash is also the default shell there.
I booted a 18.04 VM in GCE (which is based on a server install, and thus could have different defaults). The default shell there is also bash.

Where, and how, are you seeing dash as the default shell in Ubuntu 18.04? What is the change that you say was made in October 2017?

**Comment by chipaca** [comment]
Ah. Reading the issue again, I see you're dropping the snipped in `~/.bash_profile`. As the installation instructions say, you should drop them in `~/.bashrc`. `~/.bash_profile` will only get looked at for login shells.

**Comment by phil-harmoniq** [comment]
That's actually a typo. It's in my `~/.bash_aliases` which gets automatically sourced by `~/.bashrc`.

**Comment by phil-harmoniq** [comment]
This ended up being an issue with the Budgie version of Ubuntu specifically. Thanks for the help, I'll close this issue. :)

**Comment by chipaca** [comment]
To expand a little: Ubuntu Budgie ships with `/etc/profile.d/vte.sh` that gets sourced when running a shell in a VTE-based terminal (i.e. in most newer terminals, including budgie's default one), and when under bash it overwrites `PROMPT_COMMAND`. Adding the install snippet at the end of `.bashrc` (or at least after it sourced the problematic file) avoids the issue.
