### ISSUE TITLE
Home directory isn’t displayed as `~` on Fedora Silverblue

### ISSUE THREAD

**Issue by fbruetting** [justjanne/powerline-go#94]
In Fedora Silverblue everything in `/` is read-only, except for `/var/` and `/etc/` – thus `/home/` is symlinked to `/var/home/` for being writable. Powerline with default settings shows me this prompt at opening a terminal:
![bildschirmfoto von 2018-07-08 13-09-15](https://user-images.githubusercontent.com/10520767/42419199-3ac4fc46-82b0-11e8-8fae-c6b53c03a408.png)

When I execute `cd ~`, I then see the correct tilde symbol instead of that path:
![bildschirmfoto von 2018-07-08 13-16-13](https://user-images.githubusercontent.com/10520767/42419254-2c9c521c-82b1-11e8-925a-a69f88ec47ef.png)

Can you maybe detect that, so that opening full paths in `/var/home/$(USER)/…` would always show the tilde symbol instead of that longer path?

**Comment by jwflory** [comment]
@fbruetting I am curious, does Fedora Silverblue correctly note the user's home directory path in `/etc/passwd` on Linux?

**Comment by fbruetting** [comment]
Oh no, it doesn’t. I’ll report that! Would that solve the issue then?

**Comment by fbruetting** [comment]
Okay, this got fixed. @justjanne, would this then be fixed?

**Comment by justjanne** [comment]
@fbruetting I don’t have an install of Red Hat Atomic (or distros based on it) here to test. I’d love to hear if it works for you.

**Comment by fbruetting** [comment]
Seems to be resolved.
